export const TOGGLE_SEARCH_TYPE = "TOGGLE_SEARCH_TYPE";
export const FETCH_SEARCH_DATA = "FETCH_SEARCH_DATA";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_FAILURE = "FETCH_SEARCH_FAILURE";

export const FETCH_POLL_DATA = "FETCH_POLL_DATA";
export const FETCH_POLL_SUCCESS = "FETCH_POLL_SUCCESS";
export const FETCH_POLL_FAILURE = "FETCH_POLL_FAILURE";
export const TOGGLE_GRAPH_MODE = "TOGGLE_GRAPH_MODE";
