export const TOGGLE_SEARCH_TYPE = "TOGGLE_SEARCH_TYPE";
export const FETCH_SEARCH = "FETCH_SEARCH";

export const FETCH_POLL = "FETCH_POLL";
export const FETCH_POLL_DATA = "FETCH_POLL_DATA";
export const FETCH_POLL_SUCCESS = "FETCH_POLL_SUCCESS";
export const FETCH_POLL_FAILURE = "FETCH_POLL_FAILURE";
export const TOGGLE_GRAPH_MODE = "TOGGLE_GRAPH_MODE";
export const TOGGLE_VOTE_FORM = "TOGGLE_VOTE_FORM";

export const SUBMIT_VOTE = "SUBMIT_VOTE";
export const SUBMIT_VOTE_REQUEST = "SUBMIT_VOTE_REQUEST";
export const SUBMIT_VOTE_SUCCESS = "SUBMIT_VOTE_SUCCESS";
export const SUBMIT_VOTE_FAILURE = "SUBMIT_VOTE_FAILURE";

export const LOGIN = "LOGIN";
export const TOGGLE_LOGIN_FORM = "TOGGLE_LOGIN_FORM";
